name: Storybook Tests
on: workflow_dispatch
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: "9.0.6"
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: pnpm i
      - name: Install Playwright
        run: pnpm dlx playwright install --with-deps
      - name: Build Storybook
        run: pnpm turbo build
      - name: Serve Storybook and run tests
        run: |
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm dlx http-server ./apps/storybook/storybook-static --port 6006 --silent" \
            "pnpm dlx wait-on tcp:6006 && pnpm turbo test"
